/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __SWANGEOMODULE_H_
#define __SWANGEOMODULE_H_

#include <arcane/utils/Array.h>
#include <arcane/datatype/RealArrayVariant.h>
#include <arcane/datatype/RealArray2Variant.h>
#include "SwanGeo_axl.h"
#include "CartesianMesh2D.h"
#include "BathyLib.h"

using namespace Arcane;

/*** Module/Service **********************************************************/

class SwanGeoModule
: public ArcaneSwanGeoObject
{
public:
	SwanGeoModule(const ModuleBuildInfo& mbi);
	~SwanGeoModule() {}

	// entry points
	virtual void init() override;
	virtual void executeTimeLoopN() override;

	VersionInfo versionInfo() const override { return VersionInfo(1, 0, 0); }

public:
	// jobs
	virtual void computeTn();
	virtual void initDijini();
	virtual void initTime();
	virtual void initUini();
	virtual void initXc();
	virtual void updateDij();
	virtual void initDij();
	virtual void initU();
	virtual void initdeltaxdeltay();
	virtual void updateHcalc();
	virtual void initHini();
	virtual void initUcalc();
	virtual void updateDtot();
	virtual void updateHinner();
	virtual void updateHouter();
	virtual void updateHplot();
	virtual void initH();
	virtual void updateUcalc();
	virtual void iniDt();
	virtual void initHcalc();
	virtual void updateUinner();
	virtual void updateUouter();
	virtual void setUpTimeLoopN();

private:
	// mesh attributes
	CartesianMesh2D* m_mesh;

	// other attributes
	BathyLib m_bathy_lib;
	Int32 m_lastDump;
	Int32 m_n;
	Real m_deltax_lon;
	Real m_deltay_lat;
	static constexpr Real m_DEG2RAD_DP = 0.01745;
	static constexpr Real m_DEG2RAD = m_DEG2RAD_DP;
	static constexpr Real m_DEG2M_DP = 111194.9266;
	static constexpr Real m_DEG2M = m_DEG2M_DP;
	static constexpr Real m_g = -9.8;
	Real m_t_n;
	Real m_t_nplus1;
	Real m_t_n0;
};

#endif
