/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bathylibcppjni_BathyLib */

#ifndef _Included_bathylibcppjni_BathyLib
#define _Included_bathylibcppjni_BathyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bathylibcppjni_BathyLib
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bathylibcppjni_BathyLib_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     bathylibcppjni_BathyLib
 * Method:    nativeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bathylibcppjni_BathyLib_nativeDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bathylibcppjni_BathyLib
 * Method:    jsonInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bathylibcppjni_BathyLib_jsonInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bathylibcppjni_BathyLib
 * Method:    nextDepth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bathylibcppjni_BathyLib_nextDepth
  (JNIEnv *, jobject);

/*
 * Class:     bathylibcppjni_BathyLib
 * Method:    nextWaveHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_bathylibcppjni_BathyLib_nextWaveHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
