/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __IBATHYLIB_H_
#define __IBATHYLIB_H_

#include <fstream>
#include <iomanip>
#include <type_traits>
#include <limits>
#include <utility>
#include <cmath>
#include "nablalib/mesh/CartesianMesh2DFactory.h"
#include "nablalib/mesh/CartesianMesh2D.h"
#include "nablalib/utils/Utils.h"
#include "nablalib/utils/Timer.h"
#include "nablalib/types/Types.h"
#include "nablalib/utils/stl/Parallel.h"

using namespace nablalib::mesh;
using namespace nablalib::utils;
using namespace nablalib::types;
using namespace nablalib::utils::stl;

class IBathyLib
{
public:
	virtual ~IBathyLib() {};
	virtual void jsonInit(const char* jsonContent) = 0;

	virtual double nextWaveHeight() = 0;
	virtual double nextDepth() = 0;
	virtual double nextLat() = 0;
	virtual double nextLon() = 0;
};

#endif
